### ISSUE TITLE
Compiling fixes

### ISSUE THREAD

**Issue by dicamarques14** [unlimitedbacon/TTGO-DOOM#1]
I had to change the function "ttgo_touch_get_point" in "ttgo_c.cpp" to the following:

`    if (ttgo->touched())
    {
        ttgo->touch->getPoint(*x,*y);
        return true;
    } else {
        return false;
    }
`

Also, add to "platformio.ini" the TTGO library:
`
lib_deps = xinyuan-lilygo/TTGO TWatch Library@^1.4.1
`

**Comment by unlimitedbacon** [comment]
Looks like they changed the API slightly. Feel free to submit a PR for this.

**Comment by highno** [comment]
This worked for me too

**Comment by MarcosN75** [comment]
Excellent! After @dicamarques14 the API correction worked flawlessly. Amazing job, @unlimitedbacon!

**Comment by unlimitedbacon** [comment]
Huh. Guess I never noticed the PR. Sorry. Merged.
